chore: refine workflow for prod

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -1,9 +1,8 @@
 name: Deploy production
 
 on:
-  push:
-    tags:
-      - '*'
+  release:
+    types: [published]
 
 env:
   AWS_REGION: ${{ vars.AWS_REGION }}
@@ -88,3 +87,67 @@ jobs:
             --service ${{env.APP_NAME}}-${{ env.SERVICE_NAME }}-${{vars.STAGE}}-ecs-service-ECSService-HcnXKEogkl4w \
             --task-definition ${{ steps.register-task.outputs.task-definition-arn }} \
             --force-new-deployment
+
+  publish-docker-image:
+    name: publish-docker-image
+    runs-on: ubuntu-latest
+    needs: deploy
+    environment:
+      name: production
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Extract version from tag
+        id: get_version
+        run: |
+          VERSION=${{ github.event.release.tag_name }}
+          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
+
+      - name: Validate version extraction
+        run: |
+          if [ -z "${{ steps.get_version.outputs.version }}" ]; then
+            echo "Error: Version could not be extracted from the tag."
+            exit 1
+          fi
+
+      - name: Login to Docker Hub
+        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
+
+      - name: Build Docker image
+        run: |
+          echo "Building Docker image with version ${{ steps.get_version.outputs.version }}"
+          docker build -t relaybox/session:latest -t relaybox/session:${{ steps.get_version.outputs.version }} .
+
+      - name: Push Docker image
+        run: |
+          docker push relaybox/session:latest
+          docker push relaybox/session:${{ steps.get_version.outputs.version }}
+
+  update-package-version:
+    name: update-package-version
+    runs-on: ubuntu-latest
+    needs: deploy
+    permissions:
+      contents: write
+    environment:
+      name: production
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: main
+
+      - name: Update package version
+        run: |
+          VERSION=${{ github.ref_name }}
+          npm version ${VERSION#v} --no-git-tag-version
+
+      - name: Commit changes
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: 'chore: update package version [skip ci]'
+          commit_author: GitHub Actions <actions@github.com>
+          branch: main
